### ISSUE TITLE
为什么代码没了呀

### ISSUE THREAD

**Issue by 9876K** [Vivi-cookie/LabelAtt#1]

**Comment by Vivi-cookie** [comment]
在master分支

**Comment by Vivi-cookie** [comment]
![image](https://user-images.githubusercontent.com/65707124/179513210-6f127e74-ba06-4c57-99b0-a396c66a6741.png)

**Comment by 9876K** [comment]
> ![image](https://user-images.githubusercontent.com/65707124/179513210-6f127e74-ba06-4c57-99b0-a396c66a6741.png)

谢谢！谢谢！
